### PR TITLE
New variability of authorization

### PR DESCRIPTION
**Pull request by wwwhttpru**
Reworked authorization.
Rendered by AuthRefresh Interceptor.
Added AuthDelegate to implement custom authorization.
Are dynamic types now Object?.
Updated dependencies.
Updated example with new authorization.
Somewhere tests are added.

- [x] The ability to take additional fields
- [ ] Authorization tests

### CODE REVIEW

**Review by apstanisic — COMMENTED** [review]
Sorry for the wait.

I think it's a cool idea, but it's outside of this project scope. This is simple mapper to Directus REST API. Custom authentication is not supported by Directus, and should be in separate package. Same as for `BehaviorSubject`. 
If you need to use custom auth, there is a `client` property where you can access 
 Dio instance, and make any request, or add interceptors.

This PR contains bug fixes, especially for storage. Can you revert changes done to auth and leave only bug fixes?

**Comment by apstanisic** [comment]
It looks like for some reason commits can't be linked to you. Maybe you used different email? Would you like to open new PR with correct info? I can merge all commits before 4f93fa6

**Comment by wwwhttpru** [comment]
I'm sorry, I don't have enough time right now to actively participate in this.
I saw your remarks and agree to take them off.
can I delegate it all to you?

**Comment by apstanisic** [comment]
Sure, thanks for the bug fixes.
I made a draft PR that cherry picks most of the commits from this PR in #25. 
For some reason commits in this PR can't be linked to you, it credits "pashkadev" for commits. Probably due to changed info.

**Pull request closed without merging**
